# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08d724772c2d96f7246a9d8715fe981011421b11db846f224bda0bf7febfa0c7aac23b962092a3a9e3fae2e05ae5b790210a30fd604ec023d84d5f03a6ec1d97

test:
  secret_key_base: 7b47a77a5b0f00c286c2065feded4036ba488901c0c27630232b615ba2430571377cc7dfe3d4892bb6b1f909cb01b4396285318dd9de4bd378db926641a8e672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
